-- 코드를 입력하세요
SELECT TITLE, board.BOARD_ID, REPLY_ID, reply.WRITER_ID, reply.CONTENTS, DATE_FORMAT(reply.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD board join USED_GOODS_REPLY reply on board.BOARD_ID = reply.BOARD_ID where MONTH(board.CREATED_DATE) = 10
ORDER BY reply.CREATED_DATE ASC, board.TITLE ASC;
